"""add_game_map_deleted

Revision ID: 266c26c1b739
Revises: 5783a4e9e74c
Create Date: 2025-09-14 20:59:09.314126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266c26c1b739'
down_revision: Union[str, Sequence[str], None] = '5783a4e9e74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_maps', sa.Column('deleted', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_maps', 'deleted')
    # ### end Alembic commands ###
