"""add_building

Revision ID: 5783a4e9e74c
Revises: 3a5c9c6ea73c
Create Date: 2025-09-07 11:33:22.529873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5783a4e9e74c'
down_revision: Union[str, Sequence[str], None] = '3a5c9c6ea73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structures',
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('max_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structures_h'), 'structures', ['h'], unique=False)
    op.create_index(op.f('ix_structures_id'), 'structures', ['id'], unique=False)
    op.create_index(op.f('ix_structures_w'), 'structures', ['w'], unique=False)
    op.create_table('game_maps',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_maps_id'), 'game_maps', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('game_map_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_map_id'], ['game_maps.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x', 'y', 'game_map_id', name='uq_building_x_y')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_x'), 'buildings', ['x'], unique=False)
    op.create_index(op.f('ix_buildings_y'), 'buildings', ['y'], unique=False)
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_index(op.f('ix_buildings_y'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_x'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_game_maps_id'), table_name='game_maps')
    op.drop_table('game_maps')
    op.drop_index(op.f('ix_structures_w'), table_name='structures')
    op.drop_index(op.f('ix_structures_id'), table_name='structures')
    op.drop_index(op.f('ix_structures_h'), table_name='structures')
    op.drop_table('structures')
    # ### end Alembic commands ###
