"""unique

Revision ID: eba9b9902199
Revises: 6652f2259ef1
Create Date: 2025-09-26 21:09:00.618575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba9b9902199'
down_revision: Union[str, Sequence[str], None] = '6652f2259ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'resources', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    # ### end Alembic commands ###
