"""change_structure_collumns

Revision ID: fd1c8fb011e7
Revises: 266c26c1b739
Create Date: 2025-09-15 11:00:56.811859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1c8fb011e7'
down_revision: Union[str, Sequence[str], None] = '266c26c1b739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('icon', sa.String(), nullable=False))
    op.add_column('structures', sa.Column('name', sa.String(), nullable=False))
    op.add_column('structures', sa.Column('image', sa.String(), nullable=False))
    op.add_column('structures', sa.Column('enable', sa.Boolean(), server_default='True', nullable=False))
    op.alter_column('structures', 'w',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('structures', 'h',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_structures_h'), table_name='structures')
    op.drop_index(op.f('ix_structures_w'), table_name='structures')
    op.drop_column('structures', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_structures_w'), 'structures', ['w'], unique=False)
    op.create_index(op.f('ix_structures_h'), 'structures', ['h'], unique=False)
    op.alter_column('structures', 'h',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('structures', 'w',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('structures', 'enable')
    op.drop_column('structures', 'image')
    op.drop_column('structures', 'name')
    op.drop_column('structures', 'icon')
    # ### end Alembic commands ###
